### ISSUE TITLE
addResultsForCases returns error every time

### ISSUE THREAD

**Issue by evrenos** [VoloBro/testrail-api-client#16]
Hello,

When I tried to use the package for other requests I don't have any problem, such as "updateRunDescription" or "getTests" requests which take RunId as param.

On the other hand, when I try to post a result for a case by passing RunID & TestId, this is the error I face every time;
 ```
data: {
      error: 'Field :results cannot be empty but no valid tests or cases found'
    }
```

Complete error log is here;

```
Error: Request failed with status code 400
    at createError (/Users/evrenos/Desktop/sources/digibank-react-native/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/evrenos/Desktop/sources/digibank-react-native/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/evrenos/Desktop/sources/xxxx-react-native/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  config: {
    url: '/index.php?/api/v2/add_results_for_cases/1246',
    method: 'post',
    data: '{"results":[{"case_id":173558,"status_id":1,"comment":"Amazing"}]}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'x-api-ident': 'beta',
      'User-Agent': 'axios/0.21.1',
      'Content-Length': 66
    },
    auth: {
      username: 'xxxxxxx@xxxx.com',
      password: 'nAo.i4gzz91ynSxFctHq-yc7maNF16mjn4jV.XQfT'
    },
    baseURL: 'https://xxxx.testrail.io',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    'axios-retry': { retryCount: 0, lastRequestTime: 1625837675117 }
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'xxxx.testrail.io',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'infinitecsolutions.testrail.io',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 867,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'POST /index.php?/api/v2/add_results_for_cases/1246 HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'x-api-ident: beta\r\n' +
      'User-Agent: axios/0.21.1\r\n' +
      'Content-Length: 66\r\n' +
      'Host: infinitecsolutions.testrail.io\r\n' +
      'Authorization: Basic ZXZyZW5vcy5ldnJlbm9zQGV4dGVybi5maW5sZWFwLmNvbTpuQW8uaTRneno5MXluU3hGY3RIcS15YzdtYU5GMTZtam40alYuWFFmVA==\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/index.php?/api/v2/add_results_for_cases/1246',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://xxxxx@xxxx.com:nAo.i4gzz91ynSxFctHq-yc7maNF16mjn4jV.XQfT@infinitecsolutions.testrail.io/index.php?/api/v2/add_results_for_cases/1246',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'infinitecsolutions.testrail.io',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 66,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://xxxx@xxxx.xom.com:nAo.i4gzz91ynSxFctHq-yc7maNF16mjn4jV.XQfT@infinitecsolutions.testrail.io/index.php?/api/v2/add_results_for_cases/1246',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'x-api-ident': [Array],
      'user-agent': [Array],
      'content-length': [Array],
      host: [Array],
      authorization: [Array]
    }
  },
  response: {
    status: 400,
    statusText: 'Bad Request',
    headers: {
      date: 'Fri, 09 Jul 2021 13:34:36 GMT',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '76',
      connection: 'close',
      server: 'Apache',
      'access-control-allow-headers': 'authorization, content-type, x-api-ident',
      'access-control-allow-origin': 'https://testrail-lite.testrail.io',
      'set-cookie': [Array],
      vary: 'Origin'
    },
    config: {
      url: '/index.php?/api/v2/add_results_for_cases/1246',
      method: 'post',
      data: '{"results":[{"case_id":173558,"status_id":1,"comment":"Amazing"}]}',
      headers: [Object],
      auth: [Object],
      baseURL: 'https://infinitecsolutions.testrail.io',
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      'axios-retry': [Object]
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST /index.php?/api/v2/add_results_for_cases/1246 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'x-api-ident: beta\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Content-Length: 66\r\n' +
        'Host: infinitecsolutions.testrail.io\r\n' +
        'Authorization: Basic ZXZyZW5vcy5ldnJlbm9zQGV4dGVybi5maW5sZWFwLmNvbTpuQW8uaTRneno5MXluU3hGY3RIcS15YzdtYU5GMTZtam40alYuWFFmVA==\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/index.php?/api/v2/add_results_for_cases/1246',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'infinitecsolutions.testrail.io',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: {
      error: 'Field :results cannot be empty but no valid tests or cases found'
    }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

**Comment by prize477** [comment]
works fine for me with such body {"results":[{"case_id":212798,"status_id":1}]}
